### ISSUE TITLE
Mapping 5.0 parser fails on comments

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#63] opened 2017-12-04 12:02 UTC
The Map 5.0 parser generates errors on double-slash comments (following //) when there are special characters in the comment, such as colon or comma.

**Comment by cmoesel** [comment] 2017-12-07 21:06
Duplicate of standardhealth/shr-grammar#15

**Closed** 2019-02-21 12:27 UTC
