### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by dehall** [standardhealth/shr-fhir-export#119] opened 2019-01-14 15:59 UTC
Observed an infinite loop based on the current `dev` branch of `shr_spec` (`ee8d0a7ffaf2985fa0dab068060228449a8249ff`) when generating DSTU2 classes without the filter.

Further investigation suggests it's specifically related to the `shr.brca.HER2byIHC` element and this loop: https://github.com/standardhealth/shr-fhir-export/blob/v5.10.0/lib/export.js#L3146 . Based on some debugging, a `component.code` field hits that loop and always goes through the "unroll" path and the loop index is decremented, resulting in an infinite loop. (For an easy way to hit it, try debugging then waiting for a while so it gets stuck in the loop and then pause)

In case it helps, the last bit of the log before it hits the loop is below. (I don't think the error is related, but including it just in case)
```
<     --
<     mappingRule: AnatomicalLocation.AnatomicalLocationStructured maps to http://hl7.org/fhir/StructureDefinition/condition-targetBodySite
< [15:52:36.779Z]  WARN shr: Element profiled on Basic. Consider a more specific mapping. ERROR_CODE:03004 (module=shr-fhir-export, shrId=shr.base.ConditionAbsentAssertion, target=Basic)
< [15:52:36.847Z]  INFO shr: Deep path mapped to extension, but extension placed at root level. (module=shr-fhir-export, shrId=shr.base.QuestionAnswer, target=Observation)
<     mappingRule: AnatomicalLocation.AnatomicalLocationStructured maps to http://hl7.org/fhir/StructureDefinition/body-site-instance
< [15:52:36.933Z]  WARN shr: The 'code' property is not bound to a value set, fixed to a code, or fixed to a quantity unit. This property is core to the target resource and usually should be constrained. ERROR_CODE:03006 (module=shr-fhir-export, shrId=shr.base.QuestionAnswer, target=Observation)
< [15:52:36.938Z]  WARN shr: The 'value[x]' property is not bound to a value set, fixed to a code, or fixed to a quantity unit. This property is core to the target resource and usually should be constrained. ERROR_CODE:03006 (module=shr-fhir-export, shrId=shr.base.QuestionAnswer, target=Observation)
< [15:52:37.524Z]  WARN shr: Using profile that is currently in the middle of processing: shr-research-Study. ERROR_CODE:13054 (module=shr-fhir-export, shrId=shr.research.Study, target=Basic, extension=shr.entity.PartOf)
< [15:52:37.549Z]  WARN shr: Element profiled on Basic. Consider a more specific mapping. ERROR_CODE:03004 (module=shr-fhir-export, shrId=shr.research.Study, target=Basic)
< [15:52:37.600Z] ERROR shr: Invalid or unsupported target path. ERROR_CODE:13006 (module=shr-fhir-export, shrId=shr.allergy.AllergyIntolerance, mappingRule="Metadata.AuthoredDateTime maps to assertedDate")
<     target: http://fhir.org/guides/argonaut/StructureDefinition/argo-allergyintolerance
< [15:52:37.603Z] ERROR shr: Invalid or unsupported target path. ERROR_CODE:13006 (module=shr-fhir-export, shrId=shr.allergy.AllergyIntolerance, mappingRule="Metadata.InformationSource maps to asserter")
<     target: http://fhir.org/guides/argonaut/StructureDefinition/argo-allergyintolerance
< [15:52:37.708Z] ERROR shr:  (module=shr-fhir-export, shrId=brca.BreastSite, target=BodySite, extension=shr.core.DistanceFromLandmark)
<     Unexpected error adding extension. ERROR_CODE:13051 TypeError: Cannot read property 'snapshot' of null
<         at FHIRExporter.unrollElement (/Users/dehall/standardhealth/shr-fhir-export/lib/export.js:1114:31)
<         at FHIRExporter.getElementInExtension (/Users/dehall/standardhealth/shr-fhir-export/lib/export.js:2223:12)
<         at FHIRExporter.getElementInExtension (/Users/dehall/standardhealth/shr-fhir-export/lib/export.js:2247:17)
<         at FHIRExporter.applyConstraints (/Users/dehall/standardhealth/shr-fhir-export/lib/export.js:2015:32)
<         at FHIRExporter.addExtension (/Users/dehall/standardhealth/shr-fhir-export/lib/export.js:2988:10)
<         at FHIRExporter.addExtensions (/Users/dehall/standardhealth/shr-fhir-export/lib/export.js:2858:18)
<         at FHIRExporter.mappingToProfile (/Users/dehall/standardhealth/shr-fhir-export/lib/export.js:281:12)
<         at FHIRExporter.export (/Users/dehall/standardhealth/shr-fhir-export/lib/export.js:93:14)
<         at Object.exportToFHIR (/Users/dehall/standardhealth/shr-fhir-export/lib/export.js:37:25)
<         at Object.<anonymous> (/Users/dehall/standardhealth/shr-cli/app.js:286:23)
< [15:52:37.749Z]  WARN shr: Using profile that is currently in the middle of processing: brca-BreastSpecimen. ERROR_CODE:13054 (module=shr-fhir-export, shrId=brca.BreastSpecimen, target=Specimen, mappingRule="SourceSpecimen maps to parent")
< [15:52:37.844Z]  WARN shr: Overriding extensible value set constraint from http://hl7.org/fhir/ValueSet/daf-problem to http://example.com/brca/vs/BreastCancerTypeVS.  Only allowed when new codes do not overlap meaning of old codes. ERROR_CODE:03003 (module=shr-fhir-export, shrId=brca.BreastCancerDisorderPresent, mappingRule="ConditionOrDiagnosisCode maps to code")
<     target: http://fhir.org/guides/argonaut/StructureDefinition/argo-condition
< [15:52:37.854Z]  INFO shr: Deep path mapped to extension, but extension placed at root level. (module=shr-fhir-export, shrId=brca.BreastCancerDisorderPresent)
<     target: http://fhir.org/guides/argonaut/StructureDefinition/argo-condition
<     --
<     mappingRule: AnatomicalLocation.AnatomicalLocationStructured maps to http://hl7.org/fhir/StructureDefinition/condition-targetBodySite
< [15:52:37.949Z]  INFO shr: Deep path mapped to extension, but extension placed at root level. (module=shr-fhir-export, shrId=brca.BreastCancerStagePanel, target=Observation)
<     mappingRule: AnatomicalLocation.AnatomicalLocationStructured maps to http://hl7.org/fhir/StructureDefinition/body-site-instance
< [15:52:38.040Z]  INFO shr: Deep path mapped to extension, but extension placed at root level. (module=shr-fhir-export, shrId=brca.HER2ReceptorStatus)
<     target: http://fhir.org/guides/argonaut/StructureDefinition/argo-observationresults
<     --
<     mappingRule: AnatomicalLocation.AnatomicalLocationStructured maps to http://hl7.org/fhir/StructureDefinition/body-site-instance
```

**Comment by cmoesel** [comment] 2019-01-18 22:10
I think this is resolved in the beta I just released.  At any rate, I couldn't reproduce it using the beta (and I did fix one infinite loop I ran into while testing something else).

https://github.com/standardhealth/shr-cli/releases/tag/v5.15.0-beta.1

**Comment by markkramerus** [comment] 2019-08-21 18:57
Closing. Haven't seen this again (or ever).

**Closed by markkramerus** 2019-08-21 18:57 UTC
